README.md
package-lock.json
package.json
src/hosting.js
src/hosting.test.js

This adds tests for using a local SQlite database for performing greenchecks as downloadable from http://thegreenwebfoundation.org/green-web-datasets/, instead of using the API.

Add checks against local database

---

.travis.yml
package-lock.json
package.json

In sitspeed.io the Travis tests fails installing on OS X so I think it would be great to run those tests on Linux/Windows/OS X here too. That way we can fix the sqlite problem and now it will work for users co2.js
You need to enable the project on Travis https://travis-ci.org/ for this to run.
@mrchrisadams This Friday evening I've got a spot where I could help out with the SQLLite things (since its my fault since I suggested that module) and do some PRs to the repo. I need the test to pass in Travis before merging https://github.com/sitespeedio/sitespeed.io/pull/2899 - And if just install the module and run the tests here, that would be a great start for my PRs :)

Add Travis-CI tests

---

README.md
package.json
src/hosting.js
src/hosting.test.js
src/hostingAPI.js
src/hostingAPI.test.js
src/hostingDatabase.js
src/hostingDatabase.test.js

Sorry this PR introduce a couple of changes:
* Split the the hosting in multiple files for readability
* Remove the database location in the package.json file
* You need to give path to the database file when you use it
* No fallback if the database is missing, instead you will get an error
#8

Split database/API and remove database location in the package.json.

---

package.json
src/1byte.js
src/co2.js
src/co2.test.js
src/green-byte.js
src/hosting.test.js

This PR adds to things:
- it introduces the idea of the green byte model, as alluded to in #2 
- it updates the tests to an average fig for emissions, not just wifi

Intro Green Byte model, use mean energy per Gb for 1byte, and fix one number

---

src/co2.js
src/co2.test.js

This just an example of what it could look like. What I like about this approach is that we open up the API with a configuration object so when in the future when we have multiple algoritms to
calculate the CO2 emission, it can always be made backward compatible or you as a user can choose which one to use.
If you like it @mrchrisadams, I can do the same with the hosting APIs.

Classify CO2 with an option object.

---

src/co2.js

In #2, I've been addeding notes for refining the CO2 figures.
We don't have a new model, but we have been able to refine the use of the CO2 model.
This incorporates the changes for using green power, to use more consistent, like-for-like comparisons rather than comparing life cycle figures for green energy to energy only for fossil fuels.
This has the effect of making sites using renewable power look well… greener.

Update emissions figures after further research

---

.eslintrc.json
package-lock.json
package.json
src/1byte.js
src/co2.js
src/co2.test.js
src/green-byte.js
src/hosting.js
src/hosting.test.js
src/hostingAPI.js
src/hostingAPI.test.js
src/hostingDatabase.js
src/hostingDatabase.test.js
src/index.js

Ok you need to merge this manually since my class change went through is it ok?
I've set it up using default eslint settings, only exception is unused variables, I turned that rule off for now thinking we can cleanup the code later. In VSCode the setting Is automatically picked, lets see if we can make it happened your editor too,
`npm run lint` runs the tests, `npm run lint:fix` fixes the ones that can be automatically fixed. Then we can add the check to Travis + you can also make pre commit hook that either checks or auto format fit lint:fix depending on how you wanna work.

Format code using default recommended eslint settings.

---

CHANGELOG.md
src/1byte.js
src/1byte.test.js
src/co2.js
src/co2.test.js
src/hosting-api.test.js
src/hosting-database.test.js
src/hosting-json.test.js
src/hosting.test.js
src/sustainable-web-design.js
src/sustainable-web-design.test.js

This PR updates our code structure and tests to support two models.
We'd ideally have the CO2 library demonstrating that there is a degree of compatibility across the two models, without duplicating too much logic across the two.
While the tests pass, there is another PR open, #66, which addresses some of the numbers we're using, proposing we swap out some values for others ( i.e. gigabytes vs gibibytes).
I'd like to use that to review all the constants as I think some of the other carbon intensity numbers might need to be reviewed too.

Update test structure to support both models

---

src/constants/file-size.js
src/sustainable-web-design.test.js

Reverts thegreenwebfoundation/co2.js#66
Oops. I shouldn't have merged that PR yet - I was tired last night and there are bunch of other tests this change affected.
This PR when ready, should make sure we're using the `1000 * 1000 * 1000` figure for gigabytes, but have all the tests passing.

Redo the constants change - gibibyte to gigabyte calculations

---

.github/workflows/unittests.yml

Bumps GitHub Actions to their latest major versions. Main change is the runners are now using Node 16 internally instead of 12, which was EOL at end of April.
- Changelog for `actions/checkout` can be [found here](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
- Releases for `actions/setup-node` can be [found here](https://github.com/actions/setup-node/releases)

ci: bump github actions

---

.npmignore

This PR reduces the published package size from 5.6MB (17.0MB unpacked) to 14.0kB (42.3kB unpacked) by ignoring development and testing files.  The `./data/` directory contributed to most of this bloat and isn't used outside of test files.
You can see the package size by running `npm publish --dry-run`.

chore(.npmignore): reduce package size

---

.github/workflows/unittests.yml

Declares the minimum [permissions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) for CI workflows to run at the workflow level, following principle of least privilege; see [related GitHub security post](https://securitylab.github.com/research/github-actions-building-blocks/)

ci: reduce workflow permissions to minimum

---

package-lock.json
package.json

This PR:
- Bumps dependencies to their latest versions
- Bumps the lockfile version from v1 to v2; v2 is generated by NPM v7 and is backwards compatible to v1 lockfiles; [see NPM docs](https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json#handling-old-lockfiles)
- Removes unused `minimist` dependency, which was also [vulnerable to a CVE](https://security.snyk.io/vuln/SNYK-JS-MINIMIST-2429795)

build(deps): bump deps; remove unused minimist dep

---

.eslintrc.json
src/1byte.test.js
src/co2.js
src/hosting-api.js
src/hosting-database.test.js
src/hosting-json.js
src/hosting-json.test.js
src/hosting.js
src/hosting.test.js
src/sustainable-web-design.test.js

This PR:
- Replaces unnamed functions with arrow callbacks; [arrow callbacks are already in use in the repo](https://github.com/thegreenwebfoundation/co2.js/blob/4a8737a5b33c4c68ee8581f4c9507e3b0503217a/src/helpers/index.js#L1), and this saves a few bits/bytes by using less loc
- Removes already declared variables in `sustainable-web-design.test.js`; `averageWebsiteInBytes` is declared further up in the scope on line 5
-  Enables the `eslint-plugin-jest` dev dependency rules in `.eslintrc.json` and fixes errors thrown by that plugin

refactor: replace unnamed functions with arrow callbacks

---

src/co2.js

This PR swaps out use of the `url.parse()` in co2.js to in favour of the more modern cross platform WHATWG URL API instead. More below:
https://nodejs.org/api/url.html#url_url_parse_urlstring_parsequerystring_slashesdenotehost
See issue #29 fr more.

Refactor: Swap url.parse() for WHATWG URL - resolves #29

---

src/co2.test.js
src/constants/file-size.js
src/sustainable-web-design.test.js

This PR reintroduces the constants to use base 10 figures for calculations, so when we say Gigabyte we are referring to `1000 * 1000 * 1000 bytes`.
This is assuming the the original paper, when it refers to transfer in terms of gigabytes, is using the same calculation.
This should have the effect of making emissions figures  for every calculation go _up_ slightly, as the top down model that this is based on divides a set amount of energy use allocated to an entire system, then divides it by a very large number of gigabytes of transfer, to figure out a energy used for give amount of transfer.
By making the number we divide the total energy by smaller, we end up with higher energy use per byte, so we end up with higher numbers for carbon emissions as well.

Use base 10 (1000) vs base 2 (1024) for network calcs. Fixes #75

---

CHANGELOG.md
package-lock.json
package.json
src/co2.js
src/co2.test.js

This PR introduces the ability to set the model used in CO2.js to use the Sustainable Web Model with a simple string, instead of you needing to add the object yourself.
Previously you might have needed to do this
```js
import CO2 from "./co2.js";
import SustainableWebDesign from "./sustainable-web-design.js";
const co2 = new CO2({ model: 'swd' });
```
This can be awkward when consuming the distributed package from npm if you want to try out the Sustainable Web Design model in some sample code, without checking out the repo, and we haven't defined an export map to point to various models.
With this change you can now do this:
```js
import CO2 from "./co2.js";
co2 = new CO2({ model: 'swd' });
```
This is much more helpful for using in notebooks, and things like Observable for quick demos.

Allow switching of model to Sustainable Web Model using just a 'swd' string

---

src/co2.js
src/co2.test.js

This PR switches the default model used by CO2.js from OneByte to the newer Sustainable Web Design (SWD) model.
Users can now use the use the SWD model in two ways:
1. By default `const emissions = new co2()`
2. Explicitly `const emissions = new co2({ model: "swd" })`
Uses who still wish to use the OneByte model may do so by passing it as a parameter when initiating a new CO2 object.
`const emissions = new co2({ model: "1byte" })`

v0.11.0 - Use Sustainable web design model by default

---

.npmignore

Recent v0.11.x updates to the library are coming in a 17MB + in size when published to NPM. This has been raised in #108 and it was found data files were being included in the published package.
This PR fixes that & also removes the `public` directory from the package, since it is only for demonstration purposes.

ignore data files and public folder

---

src/co2.js
src/sustainable-web-design.js

This PR is a small update the recent adjustable constants in SWD PR #126.
In this PR there is one additional output, and one logic correction.
**Additional Output**
The `bytes` variable will also be returned as part of the `perVisitTrace` or `perByteTrace` results. This closes the loop, ensuring that all the inputs into the SWD formula are accounted for in the results.
```json
{
"co2": 0.00027030509999999996,
"green": false,
"variables": {
"description": "Below are the variables used to calculate this CO2 estimate.",
"bytes": 1000,
"gridIntensity": {
"description": "The grid intensity (grams per kilowatt-hour) used to calculate this CO2 estimate.",
"network": 442,
"dataCenter": 442,
"production": 442,
"device": 442
},
"dataReloadRatio": 0.02,
"firstVisitPercentage": 0.75, …
```

SWD adjustable constants update

---

index.d.ts

Adding this module declaration means that importing co2 from typescript is possible with:
`import { co2 } from '@tgwf/co2'`

Add a module declaration for use from typescript

---

package-lock.json
package.json
src/hosting-api.js
src/hosting-database.node.test.js
src/hosting-json.node.js
src/hosting-node.js
src/hosting.js
src/sustainable-web-design.js

Resolves #122.
Removes debug module completely. 
Reduces build size from:
```
166K    ./dist/cjs
41K     ./dist/esm
108K    ./dist/iife
315K    ./dist/
```
To: 
```
165K    ./cjs
41K     ./esm
76K     ./iife
282K    .
```

Removing debug

---

.github/workflows/update-average-intensities.yml
data/functions/generate_average_co2.js

This action runs `data/functions/generate_average_co2.js` which automatically updates the average intensity data.  It then creates a branch and pull request to merge updates. 
Looks like: 
Addresses: https://github.com/thegreenwebfoundation/co2.js/issues/143

Add average intensity workflow

---

src/co2.js

No user impact is expected from this change.
Background: you can ask `CO2` to return segmented results by setting the `results` option to `"segment"`. The `CO2` instance stores this flag for later.
This changes where that flag is stored. Previously, it was stored as a public property of each model. This was unused by the model and is an unnecessary mutation.
Now, the property is stored on the `CO2` instance. I believe this is easier to follow. It should also make it possible to turn the models from stateful classes into stateless objects, simplifying the code (an idea that was discussed [years ago][0]).
This new flag is explicitly marked private with the [`@private` JSDoc tag][0] and implicitly marked private by prefixing its name with an underscore; a common JS convention. (I considered …

Store segment flag on CO2 instance, not models

---

src/co2.test.js
src/sustainable-web-design.js
src/sustainable-web-design.test.js

This change:
- Adds more thorough tests for `SustainableWebDesign.prototype.perByte`
- Removes the associated tests from `co2.test.js`
- Makes a small functionality tweak: passing `perByte(n)` where `n` is less than 1 now behaves as if you called `perByte(0)`, similar to the existing `OneByte` model code
This is part of #98.

Clean up SustainableWebDesign model `perByte` tests

---

README.md
index.d.ts

The PR removes current index.d.ts file that ships with this project, and provides guidance on how to install types as a devDependency from NPM.
This closes off #77, and removes the need for further work in #168.

Use type definitions from DefinitelyTyped.

---

src/co2.js

Added new JSdoc typedef for components of CO2 estimate
Added it as a union for return types that can be total or components
Addresses part of #196

Update JSDocs to match behaviour

---

src/1byte.js
src/co2.js
src/co2.test.js
src/constants/index.js
src/helpers/index.js
src/sustainable-web-design.js
src/sustainable-web-design.test.js

Please list below any issues this pull request is related to.
- #205 
Related issue: https://github.com/thegreenwebfoundation/developer-docs/issues/50
_As clearly as possible, describe the changes made in the pull request. You should at least detail "what changes have been made" and "what the results of these changes will be"._
This change adds the [Sustainable Web Design rating …

Add Sustainable Web Design rating scale

---

src/co2.js

Please list below any issues this pull request is related to.
- #195 
It has been decided that at this time, this change will not be documented.
_As clearly as possible, describe the changes made in the pull request. You should at least detail "what changes have been made" and "what the results of these changes will be"._
This change exposes all private functions and variables that are …

export classes inside of the CO2 class

---

.github/workflows/unittests.yml
CHANGELOG.md

Please list below any issues this pull request is related to.
- #
This pull request includes updates to the GitHub Actions workflow configuration for running unit tests. The changes primarily focus on updating the supported Node.js versions to ones that are inside Nodejs own support window, and updates the actions used in the workflow to use newer versions.
Previously we were running NodeJs on …

Update supported versions of nodejs in tests

---

README.md

Please list below any issues this pull request is related to.
- #240 
Just a possible spelling correction

spelling typo corrected

---

src/constants/index.js

It might also be better longer-term to remove this comment :)
None
The Ember data pulled from the API has been returning 2023 figures for quite a while, as far as I can see the figures added to co2.js are from 2023.

Update carbon intensity comment to note the correct year
